#!/bin/sh

# configuration for the remote location
REMOTE_USER=u35698910
REMOTE_HOST=home92388257.1and1-data.host
REMOTE_DIR=kumars/vinay/milb_attendance_data

NUM_LOOPS=1
SLEEP_INTERVAL=0

for i in `seq $NUM_LOOPS`
do
    echo Running iteration $i
    python ./scrape_attendance.py  # run the script
    ls -ltr output  # see the local output
    rsync -ahzi output/ ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR} # sync
    ssh ${REMOTE_USER}@${REMOTE_HOST} ls -ltr ${REMOTE_DIR} # see the remote output
    sleep $SLEEP_INTERVAL
done